---
- name: Install Jenkins and Apache on CentOS
  hosts: n1
  become: yes
  tasks:
    - name: Install Java OpenJDK (required for Jenkins)
      yum:
        name: java-11-openjdk-devel
        state: present

    - name: Add Jenkins YUM repository
      yum_repository:
        name: Jenkins
        description: Jenkins Repository
        baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      register: jenkins_repo

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      when: jenkins_repo.changed

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Install Apache web server
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes

